project:
  type: website
  output-dir: _site
  # render:
  #   - "**/*.qmd"
  #   - "**/*.md"
  #   - "!**/*.ipynb"

website:
  title: "Gang Chen"
  description: "Professor in the Department of Atmospheric and Oceanic Sciences (AOS) at UCLA"
  site-url: https://gchenpu.github.io
  favicon: images/site-logo.png

  navbar:
    left:
      - text: "Group"
        href: group.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Code"
        href: code.qmd
    # right:
    #   - icon: github
    #     href: https://github.com/gchenpu
    #     aria-label: GitHub
    #   - icon: twitter
    #     href: https://twitter.com/gchenpu
    #     aria-label: Twitter

  page-footer:
    left: "© {{< year >}} Gang Chen"
    right:
      - text: "Built with Quarto"
        href: https://quarto.org

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    link-external-icon: false
    link-external-newwindow: true
