---
title: Larger increases in more extreme local precipitation events as climate warms
pagetitle: 2019-6-1-Li2019 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2019
author: Chao Li, Francis Zwiers, Xuebin Zhang, Gang Chen, Jian Lu, Guilong Li, Jesse
  Norris, Yaheng Tan, Ying Sun and Min Liu
venue: Geophysical Research Letters
venue_cit: <i>Geophysical Research Letters</i>, 2019GL082908, doi:10.1029/2019GL082908.
recommended_citation: 'Chao Li, Francis Zwiers, Xuebin Zhang, Gang Chen, Jian Lu,
  Guilong Li, Jesse Norris, Yaheng Tan, Ying Sun and Min Liu, 2019: Larger increases
  in more extreme local precipitation events as climate warms, <i>Geophysical Research
  Letters</i>, 2019GL082908, doi:10.1029/2019GL082908.'
paper_url: https://onlinelibrary.wiley.com/doi/abs/10.1029/2019GL082908
abstract: Climate models project that extreme precipitation events will intensify
  in proportion to their intensity during the 21st century at large spatial scales.
  The identification of the causes of this phenomenon nevertheless remains tenuous.
  Using a large ensemble of North American regional climate simulations, we show that
  the more rapid intensification of more extreme events also appears as a robust feature
  at finer regional scales. The larger increases in more extreme events than in less
  extreme events are found to be primarily due to atmospheric circulation changes.
  Thermodynamically induced changes have relatively uniform effects across extreme
  events and regions. In contrast, circulation changes weaken moderate events over
  western interior regions of North America and enhance them elsewhere. The weakening
  effect decreases and even reverses for more extreme events, whereas there is further
  intensification over other parts of North America, creating an “intense gets intenser”
  pattern over most of the continent.
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# Larger increases in more extreme local precipitation events as climate warms

*Published in Geophysical Research Letters, 2019*

**Recommended citation:** Chao Li, Francis Zwiers, Xuebin Zhang, Gang Chen, Jian Lu, Guilong Li, Jesse Norris, Yaheng Tan, Ying Sun and Min Liu, 2019: Larger increases in more extreme local precipitation events as climate warms, <i>Geophysical Research Letters</i>, 2019GL082908, doi:10.1029/2019GL082908.

## Abstract

Climate models project that extreme precipitation events will intensify in proportion to their intensity during the 21st century at large spatial scales. The identification of the causes of this phenomenon nevertheless remains tenuous. Using a large ensemble of North American regional climate simulations, we show that the more rapid intensification of more extreme events also appears as a robust feature at finer regional scales. The larger increases in more extreme events than in less extreme events are found to be primarily due to atmospheric circulation changes. Thermodynamically induced changes have relatively uniform effects across extreme events and regions. In contrast, circulation changes weaken moderate events over western interior regions of North America and enhance them elsewhere. The weakening effect decreases and even reverses for more extreme events, whereas there is further intensification over other parts of North America, creating an “intense gets intenser” pattern over most of the continent.

[Download paper](https://onlinelibrary.wiley.com/doi/abs/10.1029/2019GL082908){target="_blank"}

:::

:::
