---
title: Atmospheric River Response to Arctic Sea Ice Loss in the Polar Amplification
  Model Intercomparison Project
pagetitle: 2021-10-1-Ma2021 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2021
author: Weiming Ma, Gang Chen, Yannick Peings and Noah Alviz
venue: Geophysical Research Letters
venue_cit: <i>Geophysical Research Letters</i>, 48, 1--12, doi:10.1029/2021GL094883.
recommended_citation: 'Weiming Ma, Gang Chen, Yannick Peings and Noah Alviz, 2021:
  Atmospheric River Response to Arctic Sea Ice Loss in the Polar Amplification Model
  Intercomparison Project, <i>Geophysical Research Letters</i>, 48, 1--12, doi:10.1029/2021GL094883.'
paper_url: https://onlinelibrary.wiley.com/doi/10.1029/2021GL094883
slides_url: /files/slides/2021-10-1-Ma2021.pdf
abstract: 'The atmospheric river (AR) response to Arctic sea ice loss in the Northern
  hemisphere winter is investigated using simulations from the Polar Amplification
  Model Intercomparison Project (PAMIP). Results have shown that the midlatitude responses
  are dominated by dynamic effects. Poleward of around 60 °N, the dynamic and thermodynamic
  effects cancel each other, resulting in relatively small responses. The response
  uncertainty can be characterized by leading uncertainty modes, with the responses
  over the Pacific and Atlantic projecting onto the northeastward extension and equatorward
  shift mode, respectively. In addition, the responses seem to be mean state dependent:
  under the same forcing, models with more poleward-located climatological ARs tend
  to show stronger equatorward shifts over the Atlantic; over the Pacific, models
  with more westward-located climatological AR core tend to show stronger northeastward
  extensions. These relationships highlight the importance of improving the AR climatology
  representation on reducing the response uncertainty to Arctic sea ice loss.'
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# Atmospheric River Response to Arctic Sea Ice Loss in the Polar Amplification Model Intercomparison Project

*Published in Geophysical Research Letters, 2021*

**Recommended citation:** Weiming Ma, Gang Chen, Yannick Peings and Noah Alviz, 2021: Atmospheric River Response to Arctic Sea Ice Loss in the Polar Amplification Model Intercomparison Project, <i>Geophysical Research Letters</i>, 48, 1--12, doi:10.1029/2021GL094883.

## Abstract

The atmospheric river (AR) response to Arctic sea ice loss in the Northern hemisphere winter is investigated using simulations from the Polar Amplification Model Intercomparison Project (PAMIP). Results have shown that the midlatitude responses are dominated by dynamic effects. Poleward of around 60 °N, the dynamic and thermodynamic effects cancel each other, resulting in relatively small responses. The response uncertainty can be characterized by leading uncertainty modes, with the responses over the Pacific and Atlantic projecting onto the northeastward extension and equatorward shift mode, respectively. In addition, the responses seem to be mean state dependent: under the same forcing, models with more poleward-located climatological ARs tend to show stronger equatorward shifts over the Atlantic; over the Pacific, models with more westward-located climatological AR core tend to show stronger northeastward extensions. These relationships highlight the importance of improving the AR climatology representation on reducing the response uncertainty to Arctic sea ice loss.

[Download paper](https://onlinelibrary.wiley.com/doi/10.1029/2021GL094883){target="_blank"}

[Slides](/files/slides/2021-10-1-Ma2021.pdf){target="_blank"}

:::

:::
