---
title: More frequent atmospheric rivers slow the seasonal recovery of Arctic sea ice
pagetitle: 2023-2-1-Zhang2023 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2023
author: Pengfei Zhang, Gang Chen, Mingfang Ting, L. Ruby Leung, Bin Guan and Laifang
  Li
venue: Nature Climate Change
venue_cit: <i>Nature Climate Change</i>, doi:10.1038/s41558-023-01599-3.
recommended_citation: 'Pengfei Zhang, Gang Chen, Mingfang Ting, L. Ruby Leung, Bin
  Guan and Laifang Li, 2023: More frequent atmospheric rivers slow the seasonal recovery
  of Arctic sea ice, <i>Nature Climate Change</i>, doi:10.1038/s41558-023-01599-3.'
paper_url: https://www.nature.com/articles/s41558-023-01599-3
slides_url: /files/slides/2023-2-1-Zhang2023.pdf
abstract: In recent decades, Arctic sea-ice coverage underwent a drastic decline in
  winter, when sea ice is expected to recover following the melting season. It is
  unclear to what extent atmospheric processes such as atmospheric rivers (ARs), intense
  corridors of moisture transport, contribute to this reduced recovery of sea ice.
  Here, using observations and climate model simulations, we find a robust frequency
  increase in ARs in early winter over the Barents–Kara Seas and the central Arctic
  for 1979–2021. The moisture carried by more frequent ARs has intensified surface
  downward longwave radiation and rainfall, caused stronger melting of thin, fragile
  ice cover and slowed the seasonal recovery of sea ice, accounting for 34\% of the
  sea-ice cover decline in the Barents–Kara Seas and central Arctic. A series of model
  ensemble experiments suggests that, in addition to a uniform AR increase in response
  to anthropogenic warming, tropical Pacific variability also contributes to the observed
  Arctic AR changes.
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# More frequent atmospheric rivers slow the seasonal recovery of Arctic sea ice

*Published in Nature Climate Change, 2023*

**Recommended citation:** Pengfei Zhang, Gang Chen, Mingfang Ting, L. Ruby Leung, Bin Guan and Laifang Li, 2023: More frequent atmospheric rivers slow the seasonal recovery of Arctic sea ice, <i>Nature Climate Change</i>, doi:10.1038/s41558-023-01599-3.

## Abstract

In recent decades, Arctic sea-ice coverage underwent a drastic decline in winter, when sea ice is expected to recover following the melting season. It is unclear to what extent atmospheric processes such as atmospheric rivers (ARs), intense corridors of moisture transport, contribute to this reduced recovery of sea ice. Here, using observations and climate model simulations, we find a robust frequency increase in ARs in early winter over the Barents–Kara Seas and the central Arctic for 1979–2021. The moisture carried by more frequent ARs has intensified surface downward longwave radiation and rainfall, caused stronger melting of thin, fragile ice cover and slowed the seasonal recovery of sea ice, accounting for 34\% of the sea-ice cover decline in the Barents–Kara Seas and central Arctic. A series of model ensemble experiments suggests that, in addition to a uniform AR increase in response to anthropogenic warming, tropical Pacific variability also contributes to the observed Arctic AR changes.

[Download paper](https://www.nature.com/articles/s41558-023-01599-3){target="_blank"}

[Slides](/files/slides/2023-2-1-Zhang2023.pdf){target="_blank"}

:::

:::
