---
title: How Do Different Processes Shape Temperature Probability Distributions? A Percentile-averaged
  Temperature Tendency Decomposition
pagetitle: 2023-4-1-Quan2023 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2023
author: Heng Quan, Boer Zhang, Stephen Bourguet, Marianna Linz and Gang Chen
venue: Journal of Climate
venue_cit: <i>Journal of Climate</i>, 1--36, doi:10.1175/JCLI-D-22-0556.1.
recommended_citation: 'Heng Quan, Boer Zhang, Stephen Bourguet, Marianna Linz and
  Gang Chen, 2023: How Do Different Processes Shape Temperature Probability Distributions?
  A Percentile-averaged Temperature Tendency Decomposition, <i>Journal of Climate</i>,
  1--36, doi:10.1175/JCLI-D-22-0556.1.'
paper_url: https://journals.ametsoc.org/view/journals/clim/aop/JCLI-D-22-0556.1/JCLI-D-22-0556.1.xml
abstract: Studying temperature probability distributions and the physical processes
  that shape them is important for understanding extreme temperature events. Previous
  work has used a conditional mean temperature framework to reveal whether horizontal
  temperature advection drives temperature to extreme or median values at a specific
  location as a method to dynamically interpret temperature probability distributions.
  In this paper, we generalize this method to study how other processes shape temperature
  probability distributions and explore the diverse effects of horizontal temperature
  advection on temperature probability distributions at different locations and different
  temperature percentiles. We apply this generalized method to several representative
  regions to demonstrate its use. We find that temperature advection drives temperatures
  towards more extreme values over most land in the midlatitudes (i.e. cold air advection
  occurs during cold anomalies and warm air advection occurs during warm anomalies).
  In contrast, we find that horizontal temperature advection dampens temperature anomalies
  in some coastal summer monsoon regions, where extreme temperatures result from other
  processes, such as horizontal humidity advection and vertical temperature advection.
  By calculating the mean of processes conditioned on the temperature percentile,
  this method enables composite analysis of processes that contribute to events for
  all percentiles and a range of processes. We show examples of composites at different
  percentiles for certain processes and regions to illustrate the conditional mean
  analysis. This general approach may benefit future studies related to temperature
  probability distributions and extreme events.
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# How Do Different Processes Shape Temperature Probability Distributions? A Percentile-averaged Temperature Tendency Decomposition

*Published in Journal of Climate, 2023*

**Recommended citation:** Heng Quan, Boer Zhang, Stephen Bourguet, Marianna Linz and Gang Chen, 2023: How Do Different Processes Shape Temperature Probability Distributions? A Percentile-averaged Temperature Tendency Decomposition, <i>Journal of Climate</i>, 1--36, doi:10.1175/JCLI-D-22-0556.1.

## Abstract

Studying temperature probability distributions and the physical processes that shape them is important for understanding extreme temperature events. Previous work has used a conditional mean temperature framework to reveal whether horizontal temperature advection drives temperature to extreme or median values at a specific location as a method to dynamically interpret temperature probability distributions. In this paper, we generalize this method to study how other processes shape temperature probability distributions and explore the diverse effects of horizontal temperature advection on temperature probability distributions at different locations and different temperature percentiles. We apply this generalized method to several representative regions to demonstrate its use. We find that temperature advection drives temperatures towards more extreme values over most land in the midlatitudes (i.e. cold air advection occurs during cold anomalies and warm air advection occurs during warm anomalies). In contrast, we find that horizontal temperature advection dampens temperature anomalies in some coastal summer monsoon regions, where extreme temperatures result from other processes, such as horizontal humidity advection and vertical temperature advection. By calculating the mean of processes conditioned on the temperature percentile, this method enables composite analysis of processes that contribute to events for all percentiles and a range of processes. We show examples of composites at different percentiles for certain processes and regions to illustrate the conditional mean analysis. This general approach may benefit future studies related to temperature probability distributions and extreme events.

[Download paper](https://journals.ametsoc.org/view/journals/clim/aop/JCLI-D-22-0556.1/JCLI-D-22-0556.1.xml){target="_blank"}

:::

:::
