---
title: North American cooling signature of strong stratospheric wave events depends
  on the QBO phase
pagetitle: 2024-6-1-Ding2024 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2024
author: Xiuyuan Ding, Gang Chen and Gudrun Magnusdottir
venue: 'Environmental Research: Climate'
venue_cit: '<i>Environmental Research: Climate</i>, doi:10.1088/2752-5295/ad53f6.'
recommended_citation: 'Xiuyuan Ding, Gang Chen and Gudrun Magnusdottir, 2024: North
  American cooling signature of strong stratospheric wave events depends on the QBO
  phase, <i>Environmental Research: Climate</i>, doi:10.1088/2752-5295/ad53f6.'
paper_url: https://iopscience.iop.org/article/10.1088/2752-5295/ad53f6
abstract: Extreme stratospheric wave activity has been linked to surface cold extremes
  over North America, but little is known whether the Quasi-biennial Oscillation (QBO)
  plays a role in this linkage. Here, by comparing strong stratospheric wave events
  during the westerly phase (wQBO) with those during the easterly phase (eQBO), we
  show that the cooling signature following strong wave events depends on the QBO
  phase in observations. During wQBO, strong wave events are followed by an increased
  risk of North American cold extremes and a vertical structure shift from a westward
  phase tilt to an eastward tilt. However, strong wave events under eQBO do not change
  the cold risk nor alter the vertical tilt. We further examine this dependence on
  QBO in QBO-resolving climate models, finding that the cooling signature of strong
  wave events in models is largely insensitive to QBO phases. This insensitivity is
  suggested to be linked to model biases in the stratospheric wave representation.
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# North American cooling signature of strong stratospheric wave events depends on the QBO phase

*Published in Environmental Research: Climate, 2024*

**Recommended citation:** Xiuyuan Ding, Gang Chen and Gudrun Magnusdottir, 2024: North American cooling signature of strong stratospheric wave events depends on the QBO phase, <i>Environmental Research: Climate</i>, doi:10.1088/2752-5295/ad53f6.

## Abstract

Extreme stratospheric wave activity has been linked to surface cold extremes over North America, but little is known whether the Quasi-biennial Oscillation (QBO) plays a role in this linkage. Here, by comparing strong stratospheric wave events during the westerly phase (wQBO) with those during the easterly phase (eQBO), we show that the cooling signature following strong wave events depends on the QBO phase in observations. During wQBO, strong wave events are followed by an increased risk of North American cold extremes and a vertical structure shift from a westward phase tilt to an eastward tilt. However, strong wave events under eQBO do not change the cold risk nor alter the vertical tilt. We further examine this dependence on QBO in QBO-resolving climate models, finding that the cooling signature of strong wave events in models is largely insensitive to QBO phases. This insensitivity is suggested to be linked to model biases in the stratospheric wave representation.

[Download paper](https://iopscience.iop.org/article/10.1088/2752-5295/ad53f6){target="_blank"}

:::

:::
