---
title: 'Long-Term Trends of Northern Hemisphere Marine Cold Air Outbreaks during Boreal
  Winter: Influence of Sea Ice Retreat and Atmospheric Circulation'
pagetitle: 2025-12-1-Ran2025 - Gang Chen
body-classes: publication-page
format:
  html:
    title-block-style: none
year: 2025
author: Huanhuan Ran, Lin Wang, Thomas Spengler, Gang Chen, Ping Huang and Kaiming
  Hu
venue: Journal of Climate
venue_cit: <i>Journal of Climate</i>, e240658, doi:10.1175/JCLI-D-24-0658.1.
recommended_citation: 'Huanhuan Ran, Lin Wang, Thomas Spengler, Gang Chen, Ping Huang
  and Kaiming Hu, 2025: Long-Term Trends of Northern Hemisphere Marine Cold Air Outbreaks
  during Boreal Winter: Influence of Sea Ice Retreat and Atmospheric Circulation,
  <i>Journal of Climate</i>, e240658, doi:10.1175/JCLI-D-24-0658.1.'
paper_url: https://journals.ametsoc.org/view/journals/clim/aop/JCLI-D-24-0658.1/JCLI-D-24-0658.1.xml
abstract: Marine cold air outbreaks (MCAOs) are flows of cold air masses over relatively
  warm open oceans and are essential for the air-sea heat exchange in middle and high
  latitudes. MCAOs are intense and frequent around the Arctic and over the two western
  boundary currents and their extensions in the Northern Hemisphere. They peak in
  winter and are rare in summer. In several regions surrounding the Arctic, the wintertime
  MCAO frequency has significantly increased during the past decades and explains
  over 80\% of the wintertime trend in turbulent heat fluxes. This trend is dominated
  by MCAOs of weak and moderate intensity and is attributable to sea ice decline.
  The sea ice retreat creates new open water areas, facilitating higher frequencies
  of weak and moderate MCAOs shifting with the position of the ice edge. However,
  the frequency of strong and very strong MCAOs remains relatively stable and anchored
  to the sea ice edge. In contrast, the wintertime MCAO frequency has decreased significantly
  in the central North Pacific and the subtropical central North Atlantic, mainly
  due to the reduction of weak MCAOs. The former is associated with a shallowing of
  the Aleutian low and a negative trend of the Pacific-North American pattern. The
  latter is correlated with a positive trend of the North Atlantic Oscillation and
  the associated triple pattern in North Atlantic sea surface temperature. Although
  the MCAO-driven turbulent heat flux shows a decreasing trend in these two regions,
  sea surface temperature warming compensates for this declining trend and results
  in an insignificant change in the total turbulent heat flux trend.
---

::: {.page-with-sidebar}

::: {.sidebar-col}
{{< include /_author-profile.qmd >}}
:::

::: {.content-col}

# Long-Term Trends of Northern Hemisphere Marine Cold Air Outbreaks during Boreal Winter: Influence of Sea Ice Retreat and Atmospheric Circulation

*Published in Journal of Climate, 2025*

**Recommended citation:** Huanhuan Ran, Lin Wang, Thomas Spengler, Gang Chen, Ping Huang and Kaiming Hu, 2025: Long-Term Trends of Northern Hemisphere Marine Cold Air Outbreaks during Boreal Winter: Influence of Sea Ice Retreat and Atmospheric Circulation, <i>Journal of Climate</i>, e240658, doi:10.1175/JCLI-D-24-0658.1.

## Abstract

Marine cold air outbreaks (MCAOs) are flows of cold air masses over relatively warm open oceans and are essential for the air-sea heat exchange in middle and high latitudes. MCAOs are intense and frequent around the Arctic and over the two western boundary currents and their extensions in the Northern Hemisphere. They peak in winter and are rare in summer. In several regions surrounding the Arctic, the wintertime MCAO frequency has significantly increased during the past decades and explains over 80\% of the wintertime trend in turbulent heat fluxes. This trend is dominated by MCAOs of weak and moderate intensity and is attributable to sea ice decline. The sea ice retreat creates new open water areas, facilitating higher frequencies of weak and moderate MCAOs shifting with the position of the ice edge. However, the frequency of strong and very strong MCAOs remains relatively stable and anchored to the sea ice edge. In contrast, the wintertime MCAO frequency has decreased significantly in the central North Pacific and the subtropical central North Atlantic, mainly due to the reduction of weak MCAOs. The former is associated with a shallowing of the Aleutian low and a negative trend of the Pacific-North American pattern. The latter is correlated with a positive trend of the North Atlantic Oscillation and the associated triple pattern in North Atlantic sea surface temperature. Although the MCAO-driven turbulent heat flux shows a decreasing trend in these two regions, sea surface temperature warming compensates for this declining trend and results in an insignificant change in the total turbulent heat flux trend.

[Download paper](https://journals.ametsoc.org/view/journals/clim/aop/JCLI-D-24-0658.1/JCLI-D-24-0658.1.xml){target="_blank"}

:::

:::
