name: Publish Quarto Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Jupyter
        run: python -m pip install --upgrade pip jupyter

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Website
        run: quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
